### ISSUE TITLE
[Bug] split 和 split_once 与当前版本 alconna 不兼容

### ISSUE THREAD

**Issue by SherkeyXD** [ArcletProject/Tarina#6]
## split_once 报错示例

加载 [nonebot-plugin-kawaii-status](https://github.com/KomoriDev/nonebot-plugin-kawaii-status)

```python
Traceback (most recent call last):                                                                                                                                             
  File "/home/sherkey/Bot/Mizuki/bot.py", line 28, in <module>                                                                                                                 
    nonebot.load_from_toml("pyproject.toml")                                                                                                                                   
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml                                              
    return load_all_plugins(plugins, plugin_dirs)                                                                                                                              
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins                                             
    return manager.load_all_plugins()                                                                                                                                          
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins                                         
    return set(                                                                                                                                                                
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>                                                
    filter(None, (self.load_plugin(name) for name in self.available_plugins))                                                                                                  
> File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin                                              
    module = importlib.import_module(self._third_party_plugin_ids[name])                                                                                                       
  File "/home/sherkey/.pyenv/versions/3.12.3/lib/python3.12/importlib/__init__.py", line 90, in import_module                                                                  
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import                                                                                                              
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load                                                                                                           
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked                                                                                                  
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked                                                                                                            
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 255, in exec_module                                              
    super().exec_module(module)                                                                                                                                                
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module                                                                                                      
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed                                                                                                 
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot_plugin_kawaii_status/__init__.py", line 48, in <module>                                   
    Command("status", help_text="查看 Bot 运行状态")                                                                                                                           
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/arclet/alconna/tools/construct.py", line 485, in __init__
    head, others = split_once(command, (" ",))
TypeError: Argument 'separator' has incorrect type (expected str, got tuple)
```

报错部分的关键代码
```python
status = (
    Command("status", help_text="查看 Bot 运行状态")
    .usage("/status\n/状态")
    .action(lambda: UniMessage.image(raw=draw()))
    .build(
        block=True,
        rule=to_me(),
        aliases={"状态", "运行状态"},
        use_cmd_start=True,
        permission=SUPERUSER if plugin_config.only_superuser else None,
    )
)
```

## split 报错实例

加载 [nonebot-plugin-memes](https://github.com/noneplugin/nonebot-plugin-memes)

```python
Traceback (most recent call last):                                                                                                                                             
  File "/home/sherkey/Bot/Mizuki/bot.py", line 28, in <module>                                                                                                                 
    nonebot.load_from_toml("pyproject.toml")                                                                                                                                   
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml                                              
    return load_all_plugins(plugins, plugin_dirs)                                                                                                                              
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins                                             
    return manager.load_all_plugins()                                                                                                                                          
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins                                         
    return set(                                                                                                                                                                
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>                                                
    filter(None, (self.load_plugin(name) for name in self.available_plugins))                                                                                                  
> File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin                                              
    module = importlib.import_module(self._third_party_plugin_ids[name])                                                                                                       
  File "/home/sherkey/.pyenv/versions/3.12.3/lib/python3.12/importlib/__init__.py", line 90, in import_module                                                                  
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import                                                                                                              
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load                                                                                                           
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked                                                                                                  
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked                                                                                                            
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 255, in exec_module                                              
    super().exec_module(module)                                                                                                                                                
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module                                                                                                      
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed                                                                                                 
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot_plugin_memes/__init__.py", line 11, in <module>                                           
    from . import matchers, migrations  # noqa                                                                                                                                 
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot_plugin_memes/matchers/__init__.py", line 1, in <module>                                   
    from . import info, manage, search, help, command, statistics  # noqa                                                                                                      
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot_plugin_memes/matchers/help.py", line 21, in <module>                                      
    help_matcher = on_alconna(                                                                                                                                                 
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/nonebot_plugin_alconna/matcher.py", line 999, in on_alconna                                       
    command = AlconnaFormat(command, union=False)                                                                                                                              
  File "/home/sherkey/.pyenv/versions/MizukiBot/lib/python3.12/site-packages/arclet/alconna/tools/construct.py", line 393, in alconna_from_format                              
    strings = split(format_string.replace("{", "\"{").replace("}", "}\""), (" ",))                                                                                             
TypeError: Argument 'separator' has incorrect type (expected str, got tuple)
```

报错部分的关键代码
```python
help_matcher = on_alconna(
    "表情包制作",
    aliases={"表情列表", "头像表情包", "文字表情包"},
    block=True,
    priority=11,
    use_cmd_start=True,
)
```

## 其他信息

经过测试，0.6.0 及以上版本存在该问题，退回至 0.5.8 后该问题消失，应该和 0566cc192e29181e78f9902982469985598c2379 中的更改有关

https://github.com/ArcletProject/Tarina/blob/0566cc192e29181e78f9902982469985598c2379/src/tarina/_string_py.py#L7-L17

这里 separator 被写为 str 导致 tuple 类型的输入会报错

然后由于 alconna 那边对 split 的调用还停留在 tuple 形式，所以会导致报错

**Comment by SherkeyXD** [comment]
又或许这问题该塞到 plugin-alconna 那边去（？

**Comment by RF-Tar-Railt** [comment]
"tarina<0.7,>=0.6.3",
    "nepattern<1.0,>=0.7.4",
    "arclet-alconna<2.0,>=1.8.31",
    "arclet-alconna-tools>=0.7.10",
按这个来

**Comment by SherkeyXD** [comment]
感谢 问题解决
不过 plugin-alconna 那边是不是最好发个版把这问题解决了（x
现在旧版本的 plugin-alconna 的依赖解析可能会导致安装了 tarina 0.6+ 而 arclet-alconna 版本过旧 ~~我这问题就是这么整出来的~~

**Comment by RF-Tar-Railt** [comment]
发了
